/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.2.1/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation("com.grack:nanojson:1.7")

    compileOnly("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.6.1")
}

gradlePlugin {
    plugins {
        create("xyz.kyngs.librarian.plugin") {
            id = "xyz.kyngs.librarian.plugin"
            implementationClass = "xyz.kyngs.librarian.plugin.LibrarianGradlePlugin"
            version = project.version
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
    withJavadocJar()
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

publishing {
    repositories {
        maven {
            name = "kyngsRepo"
            url = uri(
                    "https://repo.kyngs.xyz/gradle-plugins/"
            )
            credentials(PasswordCredentials::class)
            authentication {
                create<BasicAuthentication>("basic")
            }
        }
    }
}
