/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.kyngs.librarian.java-conventions")
}

dependencies {
    api(project(":librarian-core"))
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
}

description = "librarian-paper"
