/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.kyngs.libby.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
}

description = "libby-paper"
