/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.kyngs.librarian.java-conventions")
}

dependencies {
    api(project(":librarian-core"))
    compileOnly("com.velocitypowered:velocity-api:3.1.1")
}

description = "librarian-velocity"
